nSiteNVar_tab = tabPanel("Multisite", value='multisite_exploration',
    sidebarLayout(
        sidebarPanel(
            div('Domains', class='widget-title text-center'),
            selectizeInput('DOMAINS3', label=NULL, selected=default_domain,
                choices=domains, multiple=FALSE),
                # choices=domains, multiple=TRUE, options=list(maxItems=2)),
            # div('(Choose 1 or 2; populates sites)',
            #     class='widget-subtitle text-center'),
            br(),
            div('Sites', class='widget-title text-center'),
            selectizeInput('SITES3', label=NULL, selected=default_site$hbef,
                choices=default_sitelist, multiple=TRUE, options=list(maxItems=3)),
            div('(Up to 3; populates variables)',
                class='widget-subtitle text-center'),
            br(),
            div('Variables', class='widget-title text-center'),
            selectizeInput('SOLUTES3', label=NULL,
                selected=grabvars_display_subset[[1]][[1]],
                multiple=TRUE, choices=grabvars_display_subset,
                options=list(maxItems=3)),
            div('(Up to 3)', class='widget-subtitle text-center'),
            br(),
            checkboxInput('INCONC3', value=FALSE,
                label=paste('Show input concentrations', enc2native('\U2753'))),
            br(),
            div('Unit', class='widget-title text-center'),
            div('(Applies to solutes only)',
                class='widget-subtitle text-center'),
            radioButtons('CONC_FLUX3', label=NULL,
                choices=conc_flux3_names, selected='Concentration'),
            # radioButtons('CONC_FLUX3', label=NULL,
            #     choices=c('Concentration'='Concentration',
            #         'Flux (interpolated)'='Flux', 'VWC'='VWC'),
            #     selected='Concentration'),
            conditionalPanel('input.CONC_FLUX3 == "Concentration"',
                selectizeInput('CONC_UNIT3', label=NULL, choices=conc_units,
                    selected='mg/L')
            ),
            conditionalPanel('input.CONC_FLUX3 == "Flux"',
                selectizeInput('FLUX_UNIT3', label=NULL, choices=flux_units,
                    selected='kg/ha/d')
            ),
            br(),
            div(paste('Aggregation', enc2native('\U2753')),
                class='widget-title text-center',
                title=paste('Precipitation, concentration, and flux',
                    'aggregate by mean; discharge by max')),
            radioButtons('AGG3', label=NULL, selected='Monthly',
                choices=c('Instantaneous', 'Daily', 'Monthly', 'Yearly')),
        width=3),

        mainPanel(
            fluidRow(class='text-center',
                wellPanel(
                    sliderInput("DATE3", label=NULL, min=dtrng[1], max=dtrng[2],
                        value=c(max(dtrng[2] - lubridate::days(365),
                            initial_dtrng[1], na.rm=TRUE),
                            dtrng[2]),
                        width="100%", timeFormat="%b %Y", step=30,
                        dragRange=TRUE),
                    dygraphOutput("GRAPH_PRECIP3", height='75px'),
                    br(),
                    conditionalPanel(paste('input.SOLUTES3 !== null &&',
                            'input.SITES3 !== null'),
                        div(id='main3a'),
                        dygraphOutput("GRAPH_MAIN3a", height='125px'),
                        br()
                    ),
                    conditionalPanel('input.SOLUTES3.length > 1',
                        div(id='main3b'),
                        dygraphOutput("GRAPH_MAIN3b", height='125px'),
                        br()
                    ),
                    conditionalPanel('input.SOLUTES3.length > 2',
                        div(id='main3c'),
                        dygraphOutput("GRAPH_MAIN3c", height='125px'),
                        br()
                    ),
                    div(id='flow3'),
                    dygraphOutput("GRAPH_FLOW3", height='75px')
                )
            )
        )
    )
)
