participants_tab = tabPanel('Participants', value='participants',
        style='overflow-y: scroll; overflow-x: visible;',
    div(style='padding: 20px',
        fluidRow(class='text-center',
            h2('Principal Investigators'),
            column(6,
                HTML('<p><b>Matt Ross</b><br>Colorado State</p>'),
                img(src='participants/matthew_ross.jpg',
                    style='height: 100px;'),
                br()
            ),
            column(6,
                HTML('<p><b>Emily Bernhardt</b><br>Duke</p>'),
                img(src='participants/emily_bernhardt.jpg',
                    style='height: 100px;'),
                br()
            )
        ),
        fluidRow(class='text-center',
            h2('Steering Committee'),
            column(6,
                HTML('<p><b>Jill Baron</b><br>Colorado State, USGS</p>'),
                img(src='participants/jill_baron.jpg',
                    style='height: 100px;'),
                br(),
                br(),
                HTML('<p><b>Emma J. Rosi</b><br>Cary Institute</p>'),
                img(src='participants/emma_j_rosi.jpg',
                    style='height: 100px;'),
                br(),
                br(),
                HTML('<p><b>Kaelin Cawley</b><br>NEON</p>'),
                img(src='participants/kaelin_cawley.jpg',
                    style='height: 100px;'),
                br()
            ),
            column(6,
                HTML('<p><b>Nandita Basu</b><br>University of Waterloo</p>'),
                img(src='participants/nandita_basu.jpg',
                    style='height: 100px;'),
                br(),
                br(),
                HTML('<p><b>Megan Jones</b><br>NEON</p>'),
                img(src='participants/megan_jones.jpg',
                    style='height: 100px;'),
                br()
            )
        ),
        fluidRow(class='text-center',
            h2('Data Scientists'),
            column(6,
                HTML('<p><b>Mike Vlah</b><br>Duke</p>'),
                img(src='participants/michael_vlah.jpg',
                    style='height: 100px;'),
                br(),
                br()
            ),
            column(6,
                HTML('<p><b>Spencer Rhea</b><br>Duke</p>'),
                img(src='participants/spencer_rhea.jpg',
                    style='height: 100px;'),
                br(),
                br()
            )
        ),
        fluidRow(class='text-center',
            column(12,
                HTML('<p><b>Cody Flagg</b><br>NEON</p>'),
                img(src='participants/cody_flagg.jpg',
                    style='height: 100px;'),
                br()
            )
        )
    )
)
