participants_tab = tabPanel('Participants', value='participants',
        style='overflow-y: scroll; overflow-x: visible;',
    div(style='padding: 20px;',
        fluidRow(class='text-center',
            h2('Principal Investigators'),
            column(6,
                HTML('<p class="leftpanel-text"><b>Matt Ross</b><br>Colorado State</p>'),
                img(src='participants/matthew_ross.jpg',
                    style='height: 150px;'),
                br()
            ),
            column(6,
                HTML('<p class="leftpanel-text"><b>Emily Bernhardt</b><br>Duke</p>'),
                img(src='participants/emily_bernhardt.jpg',
                    style='height: 150px;'),
                br()
            )
        ),
        br(),
        fluidRow(class='text-center',
            h2('Steering Committee'),
            column(6,
                HTML('<p class="leftpanel-text"><b>Jill Baron</b><br>Colorado State, USGS</p>'),
                img(src='participants/jill_baron.jpg',
                    style='height: 150px;'),
                br(),
                br(),
                HTML('<p class="leftpanel-text"><b>Emma J. Rosi</b><br>Cary Institute</p>'),
                img(src='participants/emma_j_rosi.jpg',
                    style='height: 150px;'),
                br(),
                br(),
                HTML('<p class="leftpanel-text"><b>Kaelin Cawley</b><br>NEON</p>'),
                img(src='participants/kaelin_cawley.jpg',
                    style='height: 150px;'),
                br()
            ),
            column(6,
                HTML('<p class="leftpanel-text"><b>Nandita Basu</b><br>University of Waterloo</p>'),
                img(src='participants/nandita_basu.jpg',
                    style='height: 150px;'),
                br(),
                br(),
                HTML('<p class="leftpanel-text"><b>Megan Jones</b><br>NEON</p>'),
                img(src='participants/megan_jones.jpg',
                    style='height: 150px;'),
                br()
            )
        ),
        br(),
        fluidRow(class='text-center',
            h2('Data Scientists'),
            column(6,
                HTML('<p class="leftpanel-text"><b>Mike Vlah</b><br>Duke</p>'),
                img(src='participants/michael_vlah.jpg',
                    style='height: 150px;'),
                br(),
                br(),
                HTML('<p class="leftpanel-text"><b>Weston Slaughter</b><br>Duke</p>'),
                img(src='participants/wes_slaughter.jpg',
                    style='height: 150px;'),
                br()
            ),
            column(6,
                HTML('<p class="leftpanel-text"><b>Spencer Rhea</b><br>Duke</p>'),
                img(src='participants/spencer_rhea.jpg',
                    style='height: 150px;'),
                br(),
                br(),
                HTML('<p class="leftpanel-text"><b>Cody Flagg</b><br>NEON</p>'),
                img(src='participants/cody_flagg.jpg',
                    style='height: 150px;'),
                br()
            )
        ),
        br(),
        fluidRow(class='text-center',
            h2('Postdocs'),
            column(6,
                HTML('<p class="leftpanel-text"><b>Amanda DelVecchia</b><br>Duke</p>'),
                img(src='participants/amanda_delvecchia.jpg',
                    style='height: 150px;'),
                br(),
                br(),
                HTML('<p class="leftpanel-text"><b>Anna Bergstrom</b><br>Duke</p>'),
                img(src='participants/anna_bergstrom.jpg',
                    style='height: 150px;'),
                br()
            ),
            column(6,
                HTML('<p class="leftpanel-text"><b>Nick Marzolf</b><br>Duke</p>'),
                img(src='participants/nick_marzolf.jpg',
                    style='height: 150px;'),
                br()
            )
        ),
        br(),
        fluidRow(class='text-center',
            h2('Graduate Students'),
            column(6,
                HTML('<p class="leftpanel-text"><b>Nicholas Gubbins</b><br>Colorado State</p>'),
                img(src='participants/nicholas_gubbins.jpg',
                    style='height: 150px;'),
                br()
            ),
            column(6,
                HTML('<p class="leftpanel-text"><b>Audrey Thellman</b><br>Duke</p>'),
                img(src='participants/audrey_thellman.jpg',
                    style='height: 150px;'),
                br()
            )
        )
    )
)
